def get_response(user_input):
    responses = {
          "hello": "Hello! How can I assist you today?",
    "bye": "Goodbye! Have a great day!",
    "how are you": "I'm just a bunch of code, but I'm here to help!",
    "help": "Sure! What do you need help with?",
    "thank you": "You're welcome! If you have more questions, feel free to ask.",
    "what's your name": "I'm an AI chatbot, here to assist you.",
    "what can you do": "I can answer questions, provide information, and more!",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what's the weather": "I can't access real-time data, but you can check a weather app!",
    "who created you": "I was created by a team of developers at OpenAI.",
    "what's the time": "I can't provide real-time information, but I can chat with you!",
    "do you have feelings": "I don't have feelings, but I'm here to help you!",
    "what's your purpose": "My purpose is to assist and provide information.",
    "can you learn": "I can learn from patterns in data but not in real-time.",
    "do you have a favorite color": "I don't have personal preferences, but blue is often calming.",
    "what's your favorite food": "I don't eat, but I hear pizza is popular!",
    "tell me something interesting": "Did you know octopuses have three hearts?",
    "can you dance": "I can't dance, but I can tell you about dancing!",
    "do you sleep": "I don't need sleep; I'm always here to chat!",
    "are you human": "No, I'm an AI chatbot designed to assist you.",
    "what's the meaning of life": "That's a deep question! Many people seek different answers.",
    "how old are you": "As an AI, I don't age. I'm as old as the latest update!",
    "what's your favorite movie": "I don't watch movies, but I know about many of them!",
    "can you play games": "I can't play games, but I can tell you about them!",
    "do you have a family": "I don't have a family, but I'm part of a larger AI system.",
    "what's your favorite book": "I don't read, but many enjoy 'To Kill a Mockingbird'.",
    "what's your favorite song": "I don't listen to music, but 'Imagine' by John Lennon is iconic.",
    "do you have a hobby": "My hobby is assisting you with your questions!",
    "what's your favorite animal": "I don't have favorites, but dogs are often loved by many.",
    "can you sing": "I can't sing, but I can tell you about music!",
    "what's your favorite sport": "I don't play sports, but soccer is widely popular.",
    "do you believe in aliens": "I don't have beliefs, but the universe is vast and full of possibilities.",
    "can you tell the future": "I can't predict the future, but I can help you with information.",
    "what's your favorite holiday": "I don't celebrate holidays, but many enjoy Christmas.",
    "do you have friends": "I don't have friends, but I'm here to chat with you!",
    "what's your favorite place": "I don't travel, but many people love visiting beaches.",
    "can you drive": "I can't drive, but I can give you driving tips!",
    "what's your favorite drink": "I don't drink, but coffee is a popular choice.",
    "do you have a pet": "I don't have pets, but many people love cats and dogs.",
    "what's your favorite season": "I don't experience seasons, but many enjoy summer.",
    "can you fly": "I can't fly, but airplanes can!",
    "do you like art": "I don't have personal tastes, but art is a beautiful form of expression.",
    "what's your favorite TV show": "I don't watch TV, but 'Friends' is a classic.",
    "can you tell a story": "Once upon a time, there was a curious user who chatted with an AI...",
    "do you have a job": "My job is to assist and chat with you!",
    "what's your favorite subject": "I don't have subjects, but many enjoy learning about science.",
    "can you write a poem": "Roses are red, violets are blue, I'm here to chat, just for you!",
    "what's your favorite game": "I don't play games, but chess is a strategic classic.",
    "do you like jokes": "I don't have preferences, but I enjoy sharing jokes with you!",
    "what's your favorite app": "I don't use apps, but many enjoy social media.",
    "can you swim": "I can't swim, but swimming is a great exercise!"
    }

    normalized_input = user_input.strip().lower()
    return responses.get(normalized_input, "I'm sorry, I don't understand that. Can you please rephrase?")


